### ISSUE TITLE
Problems with celluloid 0.16.1 (or I think so)

### ISSUE THREAD

**Issue by tonilopezmr** [dirkfabisch/mediator#52]
I had problems with celluloid 0.16.1 but I have changed in Gemfile.lock   celluloid (0.16.1) and celluloid (~> 0.16.1) (line 98) to 0.17.2 (current version).

So, when I run jekyll with the command: bundle exec jekyll serve 

````
Generating... 
                    done.
/Library/Ruby/Gems/2.0.0/gems/celluloid-0.17.2/lib/celluloid.rb:483:in `require': cannot load such file -- celluloid/essentials (LoadError)
	from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.17.2/lib/celluloid.rb:483:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/listen-2.10.1/lib/listen.rb:1:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/listen-2.10.1/lib/listen.rb:1:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-watch-1.2.1/lib/jekyll/watcher.rb:26:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-watch-1.2.1/lib/jekyll/watcher.rb:26:in `build_listener'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-watch-1.2.1/lib/jekyll/watcher.rb:7:in `watch'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:67:in `watch'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:37:in `process'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Library/Ruby/Gems/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Library/Ruby/Gems/2.0.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
	from /usr/bin/jekyll:23:in `load'
	from /usr/bin/jekyll:23:in `<main>'
```

I don't know what is happening.

Thanks you! awesome theme!

**Comment by tonilopezmr** [comment]
with: bundle update celluloid

The problem has been solved :dancer:
