### ISSUE TITLE
Error running jekyll serve in windows 10

### ISSUE THREAD

**Issue by ChrisGitter** [dirkfabisch/mediator#74]
Trying this out on Windows 10 with the newest Ruby 32 bit. No issues when installing the bundle but I can't run jekyll serve.
```
> bundle exec jekyll serve
Configuration file: E:/Work/github-blog/_config.yml
C:/Ruby23/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nokogiri-1.6.6.2-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/html-pipeline-1.9.0/lib/html/pipeline.rb:1:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/html-pipeline-1.9.0/lib/html/pipeline.rb:1:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jemoji-0.5.0/lib/jemoji.rb:3:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jemoji-0.5.0/lib/jemoji.rb:3:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `block in require_gems'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `require_gems'

        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:74:in `setup'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:36:in `initialize'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `new'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `process'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
        from C:/Ruby23/bin/jekyll:22:in `load'
        from C:/Ruby23/bin/jekyll:22:in `<main>'
```

**Comment by ChrisGitter** [comment]
Seems like it resolved itself. It didn't work initially with running `bundle exec jekyll serve` but after running just `jekyll serve` it worked and after that `bundle exec jekyll serve` works too. Maybe it was just an initial hickup? 😄 

I do get a bunch of warnings tho. But I assume nothing important ...

```
Liquid Warning: Liquid syntax error (line 23): Unexpected character # in "{{#foreach tags}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 23): Unexpected character # in "{{#if @first}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 23): Unexpected character / in "{{/if}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 23): Unexpected character / in "{{/foreach}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 39): Unexpected character # in "{{#foreach tags}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 39): Unexpected character # in "{{#if @first}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 39): Unexpected character / in "{{/if}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 39): Unexpected character / in "{{/foreach}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 77): Unexpected character / in "{{/post}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 84): Unexpected character @ in "{{@blog.url}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 23): Unexpected character # in "{{#foreach tags}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 23): Unexpected character # in "{{#if @first}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 23): Unexpected character / in "{{/if}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 23): Unexpected character / in "{{/foreach}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 39): Unexpected character # in "{{#foreach tags}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 39): Unexpected character # in "{{#if @first}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 39): Unexpected character / in "{{/if}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 39): Unexpected character / in "{{/foreach}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 77): Unexpected character / in "{{/post}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 84): Unexpected character @ in "{{@blog.url}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 44): Unexpected character # in "{{#foreach tags}}" in index.html
    Liquid Warning: Liquid syntax error (line 44): Unexpected character # in "{{#if @first}}" in index.html
    Liquid Warning: Liquid syntax error (line 44): Unexpected character / in "{{/if}}" in index.html
    Liquid Warning: Liquid syntax error (line 44): Unexpected character / in "{{/foreach}}" in index.html
    Liquid Warning: Liquid syntax error (line 66): Unexpected character # in "{{#foreach tags}}" in index.html
    Liquid Warning: Liquid syntax error (line 66): Unexpected character # in "{{#if @first}}" in index.html
    Liquid Warning: Liquid syntax error (line 66): Unexpected character / in "{{/if}}" in index.html
    Liquid Warning: Liquid syntax error (line 66): Unexpected character / in "{{/foreach}}" in index.html
    Liquid Warning: Liquid syntax error (line 88): Unexpected character / in "{{!! After all the posts, we have the previous/next pagination links }}" in index.html
```
